replicaCount: 2

image:
  repository: sevenajay/mario
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels:
  app: mario

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  port: 80
  targetPort: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

livenessProbe:
  enabled: false

readinessProbe:
  enabled: false

ingress:
  enabled: false

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
